package:
  name: exopy_hqc_legacy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
              )}}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  preserve_egg_dir: True

requirements:
  build:
    - python
    - future
  run:
    - python
    - exopy
    - numpy
    - h5py
    - pyvisa
    - pyclibrary

test:
  imports:
    - exopy_hqc_legacy

about:
  home: https://github.com/Exopy/exopy_hqc_legacy
  license: BSD
  license_file: LICENSE
  summary: Transitional package for HQCMeas
